name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Build, test and publish

    strategy:
      matrix:
        node-version: [20.x]
        dotnet-version: ['8.0.x' ]
        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: |
          dotnet restore AccordProject.Concerto.sln
          dotnet restore ConcertoJsonConverter.sln
          cd AccordProject.Concerto.Validate/concerto-validate && npm ci
      - name: Build
        run: |
          dotnet build AccordProject.Concerto.sln --configuration Release --no-restore
          dotnet build ConcertoJsonConverter.sln --configuration Release --no-restore
      - name: Test
        run: |
          dotnet test AccordProject.Concerto.sln --no-restore --verbosity normal
          dotnet test ConcertoJsonConverter.sln --no-restore --verbosity normal
      - name: Pack
        run: |
          dotnet pack AccordProject.Concerto.sln --configuration Release --no-restore /p:Version=${{ github.event.release.tag_name }}
      - name: Nuget Push
        run: |
          dotnet nuget push AccordProject.Concerto/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }}

